-- Create jobs table
CREATE TABLE IF NOT EXISTS public.jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    company_name TEXT NOT NULL,
    logo_url TEXT,
    salary TEXT,
    location TEXT,
    requirements TEXT[] DEFAULT '{}',
    posted_date DATE DEFAULT CURRENT_DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Enable RLS
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;

-- Policies
-- Everyone can view jobs
CREATE POLICY "Public jobs are viewable by everyone" ON public.jobs
    FOR SELECT USING (true);

-- Allow anon insert for seeding purposes (User should remove this after seeding if strictly needed, or refine it)
CREATE POLICY "Enable insert for everyone" ON public.jobs FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update for everyone" ON public.jobs FOR UPDATE USING (true);
