-- DANGER: This script drops existing tables to ensure schema matches the new requirements.
-- Run this only if you are okay with resetting data in these specific tables.

-- Drop tables if they exist to prevent schema conflicts and policy errors
DROP TABLE IF EXISTS public.applications CASCADE;
DROP TABLE IF EXISTS public.saved_jobs CASCADE;
DROP TABLE IF EXISTS public.jobs CASCADE; -- This relies on cascade to drop referencing FKs
DROP TABLE IF EXISTS public.companies CASCADE; -- Dropping legacy table if exists
DROP TABLE IF EXISTS public.cvs CASCADE;
DROP TABLE IF EXISTS public.profile_views CASCADE;

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. JOBS (User Provided Schema)
CREATE TABLE public.jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  company_name TEXT NOT NULL,
  logo_url TEXT,
  salary TEXT,
  location TEXT,
  requirements TEXT[] DEFAULT '{}'::TEXT[],
  posted_date DATE DEFAULT CURRENT_DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. APPLICATIONS
CREATE TABLE public.applications (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    job_id BIGINT REFERENCES public.jobs(id) NOT NULL,
    candidate_id UUID REFERENCES auth.users(id) NOT NULL,
    status TEXT CHECK (status IN ('pending', 'viewed', 'interviewing', 'offered', 'rejected')) DEFAULT 'pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. SAVED JOBS
CREATE TABLE public.saved_jobs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    job_id BIGINT REFERENCES public.jobs(id) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, job_id)
);

-- 5. CVS
CREATE TABLE public.cvs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    thumbnail_url TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. PROFILE VIEWS (Analytics)
CREATE TABLE public.profile_views (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    candidate_id UUID REFERENCES auth.users(id) NOT NULL,
    viewer_id UUID REFERENCES auth.users(id), -- Nullable if anonymous
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.saved_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cvs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profile_views ENABLE ROW LEVEL SECURITY;

-- Policies (We don't need DROP POLICY because we dropped the tables)
CREATE POLICY "Public jobs are viewable by everyone" ON public.jobs FOR SELECT USING (true);

CREATE POLICY "Users can see their own applications" ON public.applications FOR SELECT USING (auth.uid() = candidate_id);
CREATE POLICY "Users can create applications" ON public.applications FOR INSERT WITH CHECK (auth.uid() = candidate_id);

CREATE POLICY "Users can see their saved jobs" ON public.saved_jobs FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can manage saved jobs" ON public.saved_jobs FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Users can see their own CVs" ON public.cvs FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can manage their own CVs" ON public.cvs FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Users can see their profile views" ON public.profile_views FOR SELECT USING (auth.uid() = candidate_id);
